import { Injectable } from "@angular/core";
import {
  doc,
} from "@angular/fire/firestore";
import { serverTimestamp, setDoc } from "firebase/firestore";
import { Profile } from "../models/profile";
import { DbService } from "./db-service";

@Injectable({ providedIn: "root" })
export class ProfileService extends DbService<Profile>{


  constructor() {
    super();
    this.COLLECTION = "profiles"
  }

  /** Create a Profile and return its new id. */
  async create(data:Profile): Promise<string> {
    if(!this.user()){
      throw new Error("login please")
    }
    const newDocRef = doc(this.db, this.COLLECTION, this.user().uid);
    const docId = newDocRef.id; // Retrieve the generated document ID

    await setDoc(
      newDocRef,
      {
        ...data,
        userId: this.user().uid, //use the uid generated by google auth to ensure same id in storage
        createdAt: serverTimestamp(),
        updatedAt: null,
      },
      { merge: true }
    );

    return docId;
  }

}